strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
socks5  127.0.0.1 1080 # Uncomment to connect to Pivot 1 network
#socks5  127.0.0.1 1081 # Uncomment to connect to Pivot 2 network
#socks5  127.0.0.1 1082 # Uncomment to connect to Pivot 3 network
#socks5  127.0.0.1 108X # Uncomment to connect to Pivot X network
